### ISSUE TITLE
ES6 NPM package is not useable by most. ES5 transpile needed

### ISSUE THREAD

**Issue by grempe** [lgaticaq/diceware-generator#6]
Hello,

I like the changes you've made in this fork, but unfortunately I (and I'm sure many others) cannot
make use of this package directly since it only presents the ES6 `src/index.js` file and most consumers of this package will need an ES5 transpiled version in order to use it. This is especially true for the many who minification tools like UglifyJS, none of which as I understand it yet support ES6 code (that breakage is what lead me down this path).

The issue and a possible solution are outlined here:

http://jamesknelson.com/writing-npm-packages-with-es6-using-the-babel-6-cli/

In my earlier pull request I included a simple `npm run build` command which transpiled the ES6 source and included it in the repo. It also indicated in `package.js` that this `lib` dir contains the main file for package consumers to use.

While I am no expert by any means in the nuances of transpiling, this solution worked quite well for me when including it in a Vue.js app which runs all ES5 code through UglifyJS.

I recreated that solution in a new branch of mine which does the same task, but also recompiles whenever the tests are run and uses the ES5 file as the target for the tests to ensure everything is working right.

Here is that commit:

https://github.com/grempe/diceware-generator/commit/9c1863189f9d8cb48978ec5deb40c1571239cc86

I'd like to understand why you removed this from my original pull request, and also whether you are open to finding a solution for this. I'd rather not have to rely on my private fork and forked NPM package.

Cheers.

**Comment by lgaticaq** [comment]
I removed babeljs because the min version specified is node v4. The syntax used is supported by that version and modern web browsers. In your case it gives you problems when building the package with Vuejs?

**Comment by grempe** [comment]
Yes, it breaks when webpack passes it to UglifyJS. The transpiled version works fine.

**Comment by grempe** [comment]
FYI, this is the error I see when using v3.0.0 with webpack + UglifyJS:

```
ERROR in build.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/diceware-generator/src/index.js:5,0]
```

**Comment by lgaticaq** [comment]
Fix with last release

**Comment by grempe** [comment]
Boom!  Works out of the box for me now.  I'll be removing my fork and private NPM package. Thanks.
