### ISSUE TITLE
Feature request, lazy load only language packages that are already installed

### ISSUE THREAD

**Issue by grempe** [lgaticaq/diceware-generator#7]
The problem I ran into is when importing this package into a Vue.js application. Vue.js compiles everything down to a single build.js artifact that represents the entire single-page app that I am working on. Since diceware-generator declares runtime dependencies on a number of language packages, those also unfortunately get installed and baked into the find build.js file. This greatly increases the resulting file size to an unacceptable degree.

In order to work around this I have had to create a private branch that only requires the `enEFF` package.

https://github.com/grempe/diceware-generator/commit/9a6a36a57335c1681b746db94afe285471464c6c

As you can imagine, if the diceware-generator grows to include other language packages (which I would be happy to help with as I already have a lot of them for a less well factored app running here:  https://www.rempe.us/diceware/#eff )

What I would love to see happen is something like the following:

```
\\ core package and two lang packs
npm install diceware-generator diceware-generator-en diceware-generator-en-eff
```

```
\\ OK : if the language specified in the options Object was detected to be installed then use it.
dwGen({language: 'en', wordcount: 6, format: 'string'});

\\ FAIL : if the language specified in the options Object was not detected throw an error.
dwGen({language: 'zh', wordcount: 6, format: 'string'});
```

This approach would greatly help in reducing the footprint of this package. As it is now it cannot scale. Every additional language that a packager wants to support requires pull requests to the core package, and every consumer of the core package needs to install _every_ lang pack that is supported in this way.  It would be much nicer to find a way to decouple the two.

**Comment by lgaticaq** [comment]
Great idea. I think it is best to separate language packs and include an instance in the options.

Like this:

``` javascript
const dwGen = require('diceware-generator');
const enEff = require('diceware-wordlist-en-eff');

const options = {
  language: enEff,
  wordcount: 6,
  format: 'string'
}
const pass = dwGen(options);
```

**Comment by lgaticaq** [comment]
Already with last release

**Comment by grempe** [comment]
I have not tried it out yet, but the new release commits look great and I like the approach you took.
